
import os
import re
import subprocess as sp
import tempfile as tem


def code_extraction(code:str)->str:
    """ 
    Input:
        Code:(STR) input the code generated by the llm .
    =========================================================
    Outpus:
        code:(STR) removes comemnts or any other things egenrated by llm and provides only verilog code.
    """
    pattern=r"module\s+\w+.*?endmodule"
    # pattern = r"```(?:verilog|systemverilog)?\s*(module\b.*?endmodule)\s*```"
    matches=re.findall(pattern=pattern,string=code,flags=re.DOTALL)
    clean_code=matches[0]
    return clean_code


def linter(code:str)->dict:
    """
    Input :
        code as string,
    -------------------------------- 
    Outputs:
        dict consisting returncode , stdout, stderr.
    ============================================================================================== 
    If return code == 0 then the stderr might be nothing or might have warnings (not errors but warnings). 
    Uses Verilator to run the linter for checking  the syntax of verilog code.
    """
    temp_filename=None
    try:
            with tem.NamedTemporaryFile(
            mode="w",suffix=".v",delete=False,
            ) as temp_file:
                temp_file.write(code)
                temp_file.flush()
    
                temp_filename=temp_file.name
                terminal=[
                          "verilator",
                          "--lint-only",
                          "-Wall",
                          "-Wno-fatal",
                          "-Wno-DECLFILENAME",
                          "-Wno-EOFNEWLINE",
                           temp_filename,
                ]
                result=sp.run(terminal,capture_output=True,text=True,check=False)
                return {
                    "return_code":result.returncode,
                    "stdout":result.stdout,
                    "stderr":result.stderr
                }
    except sp.CalledProcessError as e:
            return {
                "return_code": -1,
                "stdout": "",
                "stderr": f"lint_tool exception: {type(e).__name__}: {e}"
            }
    finally:
            if temp_filename and os.path.exists(temp_filename):
                os.remove(temp_filename)


def Top_Type(code:str)->dict:
    """
    INPUT:
    --------
    Code : string,
    ==================
    OUTPUT:
    --------------
    top_name:str,
    type:SEQ|COMB
    DICT consisiting of 
    1)  top module name
    2) Type of circuit sequential ro combinaitonal circuit
    Using yosys to get automatic top module name and type of circuit . 
    """
    temp_filename=None
    top_mod_patt=r"=+\s+(\w+)\s+=+"
    type_patt= r"\b\d+\s+\$(?:dff|adff|sdff|dlatch)\b"
    source_foder="./src"
    x="combinational"
    try:
                with tem.NamedTemporaryFile(
                mode="w",suffix=".v",delete=False,
                ) as temp_file:
                    temp_file.write(code)
                    temp_file.flush()
        
                    temp_filename=temp_file.name
                    cmd=["yosys",
                             "-p",
                             f""" 
                             read_verilog {temp_filename};
                             proc;
                             stat;
                            """
                             ]
                    out=sp.run(cmd,capture_output=True,text=True,check=False)
                    top=re.search(pattern=top_mod_patt,string=out.stdout,flags=re.DOTALL)
                    typ=bool(re.search(pattern=type_patt,string=out.stdout,flags=re.DOTALL))
                    if typ:
                          x="sequential"
                    os.makedirs(name=source_foder,exist_ok=True)
                    top_module_name = top.group(1) if top else "unknown_top"
                    file_name=f"{top_module_name}.v"
                    file_path=os.path.join(source_foder,file_name)
                    with open(file_path,"w") as f:
                          f.write(code)
                    return{
                          "top_module":top,
                          "type":x,
                          "output":out.stdout,
                          "return_code":out.returncode,
                          "err":out.stderr
                    }

    except Exception as e: # noqa: BLE001
         return {"Error":e}
    
    


def netlist(top:str,module_path:str,lib_path:str)->dict:
    """
    Inupt: 
          1) top-> top moduel name,
          2) module_path -> provide top module path,
          3) lib_path ->  provide path for the tech lib used for netlist generation,
    Output:
        returncode: 0 if successful else any integer when we get error
        stdout: standaroutput for runngin the code in command promt migth be null.
        stderr: error caused due to unsuccessful run.
    """
    try:
        cmd=['yosys',
            '-p',
            f"""
            read_verilog {module_path};
            hierarchy -top {top};
            proc;
            opt;
            memory;
            opt;
            fsm;
            opt;
            techmap;
            opt;
            abc -liberty {lib_path};
            clean;
            write_verilog -noattr {top}_netlist.v;
            show -format dot -prefix {top};
            """
            ]
        out=sp.run(cmd,capture_output=True,text=True,check=False)
    except Exception as e: # noqa: BLE001
        return {
            "netlist_returncode":"-1",
            "netlist_stdout":"Error in netlsit generation.",             
            "netlist_stderr":e}
    return {
        "netlist_returncode":out.returncode,
        "netlist_stdout":out.stdout,
        "netlist_stderr":out.stderr
    }





